name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    name: Linting
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up node
        uses: actions/setup-node@main
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: ${{ github.workspace}}/yarn.lock

      - name: Install node dependencies
        working-directory: ${{ github.workspace}}
        run: yarn install

      - name: Run linting
        working-directory: ${{ github.workspace}}
        run: yarn lint

  unit-tests:
    name: Unit tests
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up node
        uses: actions/setup-node@main
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: ${{ github.workspace}}/yarn.lock

      - name: Install node dependencies
        working-directory: ${{ github.workspace}}
        run: yarn install

      - name: Run tests
        working-directory: ${{ github.workspace}}
        run: yarn test

  build:
    name: Build
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up node
        uses: actions/setup-node@main
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: ${{ github.workspace}}/yarn.lock

      - name: Install node dependencies
        working-directory: ${{ github.workspace}}
        run: yarn install

      - name: Build
        working-directory: ${{ github.workspace}}
        run: yarn build
